version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=pgg
    #   - MONGO_INITDB_ROOT_PASSWORD=pgg
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=pgg
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pgg
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      # - ME_CONFIG_MONGODB_URL=mongodb://pgg:pgg@mongodb:27017/
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      # - MONGODB_URI=mongodb://pgg:pgg@mongodb:27017
    ports:
      - 9216:9216
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=pgg
      - GF_SECURITY_ADMIN_PASSWORD=pgg
    ports:
      - 3000:3000
    depends_on:
      - prometheus

