version: '3.8'

services:
  mongodb:
    #image: mongo:latest
    image: mongo:4.2
    container_name: mongo_test
    restart: always
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-data:/data/db
